### PR TITLE
Fixed **many** Clippy lints, and one bug.

### PR DESCRIPTION
**Pull request by Dygear**
This is mostly a Clippy lint fix. A fair number of using match statements for a single value that were converted to `if let Some()`; A few areas where the `format!` macro was used for naked strings where Clippy wants `.to_string()` used; And one lifetime that was no longer used.

The only bug fix that comes in here was with the menu where menu_action and key_action were not named distinctly and so always took the branch as they were identical values being compared.

Answers #78

### CODE REVIEW

**Comment by Dygear** [comment]
It's probably worth a mention that that is one Clippy lint remaining, regarding the function signature of `draw_rect` in src/text_box.rs. It doesn't like that there are 8 args to this function. I looked into the function itself, it's called in three locations so a refactor here wouldn't kill me, but I also don't understand the function in order to do this properly.

```RUST
fn draw_rect(
    buffer: &mut [u32],
    image_w: i32,
    image_h: i32,
    start_x: i32,
    start_y: i32,
    w: i32,
    h: i32,
    cosmic_color: cosmic_text::Color,
)
```

I think `image_w` and `image_h`, `start_x` and `start_y`, and `w` and `h` could be moved into their own structs.

```RUST
// Was `image` & and the naked offsets.
struct Canvas {
    w: i32,
    h: i32,
}

struct Offset {
    w: i32,
    y: i32,
}
```

That changes the function declaration to.


```RUST
draw_rect(
    buffer: &mut [u32],
    image: Canvas,
    start: Start,
    offset: Canvas,
    cosmic_color: cosmic_text::Color,
)
```

But that seems just a little on the bike sheddy side, and doesn't actually talk to the `TODO` right above the function for its performance to be improved. I am at this point, not the person for that job as I don't fully understand the implications of the math in this function as of yet.

**Comment by Dygear** [comment]
Ok, the draw_rect refactor actually helps makes some more sense of the code. But please really scrutinized that commit. I might have screwed something up during that refactor and I wouldn't know it.

**Comment by Dygear** [comment]
After spending about an hour I understand most of the draw_rect function. I've changed the variable names to denote where they interact with the drawing surface. The `window` arg now describes the width `w` and the height `h` of the window itself. The `screen` arg denotes that actual pixel being drawn across the whole screen. (I don't _yet_ know how that works with multiple monitors. It could be worth the argument that actually the screen should be called `canvas` where the physical pixels of a screen is actually a window into this canvas, and windows are `portals` in the application, but that's really a question for a Wayland dev.).

**Comment by Dygear** [comment]
Oh, I should probably mention that I changed from column major (y first loop), to row major (x first loop) when writing pixels. The pixels in the buffer start at `x` and then go `x`, `y` + `1`, until y gets to it's max y value, then handles the next row of pixels. I think that putting this into a ring buffer might help with speed when it comes to scrolling text (that should happen more often that a window resize, so we should optimize for that case.) As when we scroll the text area we scroll whole lines, we could in a ring buffer change the head pointer to be `canvas.w * line_height_px * sizeof(u32)` further into the buffer, then we invalidate and update the tail pointer by the same offset and only redraw those pixels. Because it's a ring buffer, we get scrolling for very cheap.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
