### PR TITLE
better sorting of name files

### PR DESCRIPTION
**Pull request by wiiznokes**
Now 
- `9` is sown before `10`
- `A` and `a` will be next to each other

### CODE REVIEW

**Comment by jackpot51** [comment]
It would be nice if the new Lexeme code was moved to a new file.

**Comment by wiiznokes** [comment]
There you go, let me know if you're happy about naming

**Comment by jackpot51** [comment]
I'm using https://docs.rs/lexical-sort in cosmic-files, I think I'd rather use that to not have a custom implementation here.

**Comment by jackpot51** [comment]
Done in https://github.com/pop-os/cosmic-edit/commit/e3bc82f0f369d55f0fe6b5b8042455e401dacc7c

**Pull request closed without merging**
