### PR TITLE
Implemented background calculation and word count for document statistics 

### PR DESCRIPTION
**Pull request by Aquilesorei**

### CODE REVIEW

**Review by Dygear — COMMENTED** [review]
The vast majority of this commit is moving code around. The 5 lines that are added (1344 - 1348) are however valuable for a usability standpoint. But the bulk of this code change for this commit is moving the functions subscription and context_drawer in the src/main.rs file. Are these changes strictly needed, it kind of obfuscates the actual code changes here.

**Comment by Dygear** [comment]
Nice job on the word count implementation, that looks good to me.

**Comment by Aquilesorei** [comment]
Thanks for your feedback on the commit. I understand your concern about the amount of code movement .

 I reorganized the functions in src/main.rs from smallest to largest, primarily for readability purposes. This can make it easier to understand the code's structure and flow, especially for those unfamiliar with the codebase.
The function movements themselves don't alter the code's functionality. They were done solely to enhance maintainability and clarity.

**Comment by Dygear** [comment]
> Thanks for your feedback on the commit. I understand your concern about the amount of code movement .
> I also make commits by feature even if it takes 5 lines.

I agree having a feature on its own commit is the correct approach. The moving of functions around as their own commit would make sense to me, but the actual code change in that commit (#[198ffde](https://github.com/pop-os/cosmic-edit/pull/92/commits/198ffde4cd8be10b3d35544097221c02c163ba06)) this is the real change here:

```RUST
                // clear textfields values  when search widget is closed
                 if self.find_opt.is_none(){
                     self.find_search_value.clear();
                     self.find_replace_value.clear();
                 }
```

But also has the functions moving around making that commit makes that change harder to find. It's 5 lines here, but the commit has +186 −145 because of the function moves. Now this is not a huge deal here, but will make things harder to track later on with larger commits. Worth a mention.

**Pull request closed without merging**
