### PR TITLE
Added Wrap Around functionality to Find and Replace menu

### PR DESCRIPTION
**Pull request by RaspberryProgramming**
I also added language support for English and a few others

### CODE REVIEW

**Comment by jackpot51** [comment]
Where did the translations come from?

**Comment by RaspberryProgramming** [comment]
Google translate, but I can recreate this or without them if it's an issue.

**Comment by jackpot51** [comment]
I recommend to only fill in translations for languages you know to avoid errors.

**Comment by RaspberryProgramming** [comment]
@jackpot51 Thanks, I just reverted the commit.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
