### PR TITLE
[WIP] Saving Modified Files on Close

### PR DESCRIPTION
**Pull request by Dygear**
Answers #60. Added a `modified` field to the `EditorTab` struct. Currently banging my head against .iter() function for `self.tab_model.iter()` as it borrows self is immutable and I need to be able to use `EditorTab.save()` that requires a mut refrence. Currently .iter_mut() is not implemented for [`impl<SelectionMode: Default> Model<SelectionMode>`](https://github.com/pop-os/libcosmic/blob/master/src/widget/segmented_button/model/mod.rs#L295) in `libcosmic` so this is a WIP.

### CODE REVIEW

**Comment by mmstick** [comment]
The keys are copyable integer pairs. You could store the keys to be saved in a Vec, and then access it mutably.

**Comment by Dygear** [comment]
@mmstick Thanks for the tip. Think I saw so deep into it that I couldn't see the forest for the trees. Looks like I'm going to have to build a save dialog prompt for this. Also noticed that when I press the `X` button in the top right corner that doesn't send the `Message::Quit`. I don't think Iced handles that message or at least I don't know if that's true as of yet. Perhaps the best way to handle it right now is to manually implement the Drop method on App so that the quit function is called and file saves can happen.

**Comment by mmstick** [comment]
It may need an update to libcosmic. There was a time when the message was not being handled.

**Comment by Dygear** [comment]
Looks like #84 handles that `libcosmic` update, as the slug changes.

**Comment by RefinedSoftwareLLC** [comment]
I am not sure if this high level list will help with any of this pull request's low level improvements (This is just a list I made and is not offical): [Backup Unsaved Changes #94](https://github.com/pop-os/cosmic-edit/issues/94#issue-2080385765)

**Comment by Dygear** [comment]
I may remote this later, but right now I've not been able to figure our how to make my own dialog box. Will work on this in the future, but there is some other low hanging fruit to get to first.

**Pull request closed without merging**
